[package]
name = "conventional-commits-parser"
description = "A parser for the conventional commits specification"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
